title: Sijo Alex
#logo: /assets/img/image.png  # Updated to use your image file path
# description: Data Scientist, Machine Learning Enthusiast, MBA Student
show_downloads: true
theme: jekyll-theme-minimal

# Social links
social_links:
  email: "sijoalex157@gmail.com"
  linkedin: "https://www.linkedin.com/in/sijo-alex-82321717a/"
  ieee_paper: "https://ieeexplore.ieee.org/document/10493586"

# Navigation links
nav:
  - name: "Home"
    url: "/"
  - name: "Projects"
    url: "/projects"
  - name: "Experience"
    url: "/experience"
  - name: "Education"
    url: "/education"
  - name: "Contact"
    url: "/contact"

# Author Information
author:
  name: "Sijo Alex"
  email: "sijoalex157@gmail.com"
  linkedin: "https://www.linkedin.com/in/sijo-alex-82321717a/"

# Build settings
markdown_ext: "md"
